### PR TITLE
Synchronize with documentation in main repository

### PR DESCRIPTION
**Pull request by felixwiemuth**
This fix was already done in the spacemacs repository: https://github.com/syl20bnr/spacemacs/commit/2a0f15c83688c1008cd7117627acfdcd33760279

### CODE REVIEW

**Comment by nashamri** [comment]
The documentation is in-sync with the `develop` branch of the website (https://github.com/syl20bnr/develop.spacemacs.org) and will be pushed to the main website once a new spacemacs version is released.

**Comment by felixwiemuth** [comment]
Ok sorry, didn't know about this structure. A bit unlucky though that the fix is already months old and not online yet...

**Comment by nashamri** [comment]
Yeah well hopefully a new version will be released soon :smile: 
and you can always visit the `develop` website here: http://develop.spacemacs.org/

**Comment by nashamri** [comment]
For the above mentioned reasons, can you please close this PR?
Thanks.

**Pull request closed without merging**
